project_id = "efnvvakomsyypmalfrba"

[functions.ai-interview]
verify_jwt = false

[functions.ai-resume]
verify_jwt = false

[functions.evaluate-code]
verify_jwt = false

[functions.generate-aptitude]
verify_jwt = false

[functions.generate-coding-problems]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
